# dataset: mssd-3d-all
embedder: DuoRec
# n_epochs: 30
# val_epoch: 5
batch_size: 512
hidden_size: 100
n_layers: 1
n_heads: 1
final_act: relu
embedding_dim: 100
lr: 0.001
loss_type: CE
maxlen: 19
dropout0: 0.0
dropout1: 0.0
temperature: 10
lamb: 0.1
lamb_sem: 0.1
ssl: us_x
sim: cos
semantic_type: context_shuffle
