# dataset: mssd-3d-all
embedder: NISER
# val_epoch: 5
# n_epochs: 30
batch_size: 512
hidden_size: 100
embedding_dim: 100
n_layers: 1
lr: 0.001
dropout0: 0.25
loss_type: CE
scaling_factor: 1
maxlen: 19